# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 868278c80dee2bd49c713847d1a92a4118fa472124665f37b1f24bea86a4e40362b9899e4cdf07c27806351800e11319215cbed86bfd64d6a5bb3207f45b5bc5

test:
  secret_key_base: 3137523e7a633563e916a4ffb5856ac03885ebfe667383ee47e7f3b1682149424363a37e5ff39883f2ab07b7af3eec00a38ed81cb305626ed06fb3ab22144a04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
